#include "pico/stdlib.h"
#include "hardware/adc.h"
#include "arm_math.h"
#include "arm_const_structs.h"
#include "lis3dh.h"
#include "tasks/accelerometer.h"
#include "microphone.h"
#include "leds.h"
#include "board.h"
#include <cstdio>   
#define SAMPLE_COUNT 1024



void leds_iteration() {
    static int pos = 0;                 // static variable to keep track of the current LED position

    clear_leds();                       // clear all LEDs
    set_led(pos, 0, 255, 0);            // green LED at current position
    show_leds();                        // send data to LEDs

    pos = (pos + 1) % NUM_LEDS;         // cycle through LEDs
}

void accelerometer_init_once() {
    lis3dh_init(i2c0, I2C_SDA_PIN, I2C_SCL_PIN);
    init_leds();                       
}

void accelerometer_iteration() {
    int16_t raw_x, raw_y, raw_z;
    lis3dh_read_raw_xyz(&raw_x, &raw_y, &raw_z);

    float x_g = convert_raw_to_g(raw_x);
    float y_g = convert_raw_to_g(raw_y);
    float z_g = convert_raw_to_g(raw_z);

    printf("X=%.3f g  Y=%.3f g  Z=%.3f g\n", x_g, y_g, z_g);

    //controlling LEDs with Y-axis acceleration
    int led_index = map_to_led_index(y_g);

    clear_leds();
    set_led(led_index, 0, 255, 0); 
    show_leds();
}


// Hanning window
const int16_t hanning_window[SAMPLE_COUNT] = {
    #include "hanning_window_q15.inl" // 1024 Q15 values ​​generated by MATLAB
    };
    
    // FFT and data buffer
    arm_rfft_instance_q15 fft_instance;
    
    uint16_t adc_buffer[SAMPLE_COUNT]; // Raw ADC sample data
    int16_t time_buffer[SAMPLE_COUNT]; // Debiased + left-shifted Q15 format signal
    q15_t fft_output[SAMPLE_COUNT]; // FFT output (complex: alternating real and imaginary parts)
    q15_t magnitude_buffer[SAMPLE_COUNT/2]; // Magnitude squared (spectral energy)
    
    // FFT bins for each LED Interval (log scale distribution)
    const uint16_t bin_edges[13] = {
    6, 8, 11, 16, 24, 35, 51, 75, 110, 161, 237, 349, 513
    };
    
     void microphone_init_once() {
        microphone_init();                                    // ADC + FIFO
        init_leds();                                          // WS2812
        arm_rfft_init_q15(&fft_instance, SAMPLE_COUNT, 0, 1); // CMSIS FFT
    }
    // Apply window function to signal
    void apply_window(int16_t* buffer) {
    for (int i = 0; i < SAMPLE_COUNT; ++i) {
    int32_t temp = (int32_t)buffer[i] * hanning_window[i];
    buffer[i] = (int16_t)(temp >> 15); // Return to Q15 range
    }
    }
    
    // Map spectral energy to LED
    void display_fft_on_leds(const q15_t* magnitudes) {
    for (int led = 0; led < 12; ++led) {
    uint16_t start = bin_edges[led];
    uint16_t end = bin_edges[led + 1];
    
    uint32_t sum = 0;
    for (int i = start; i < end; ++i) {
    sum += magnitudes[i];
    }
    
    uint32_t avg = sum / (end - start);
    uint8_t brightness = avg >> 7; // Adjust scaling factor
    if (brightness > 255) brightness = 255;
    
    set_led(led, 0, brightness, 0);  

    }
    show_leds();
    }
    
    void microphone_iteration() {
    microphone_read(adc_buffer, SAMPLE_COUNT);
    
    // Step 2: Calculate DC bias
    int32_t sum = 0;
    for (int i = 0; i < SAMPLE_COUNT; ++i) sum += adc_buffer[i];
    uint16_t dc_bias = sum / SAMPLE_COUNT;
    
    // Step 3: Debias + left shift + limit → Q15 format
    for (int i = 0; i < SAMPLE_COUNT; ++i) {
    int32_t temp = ((int32_t)adc_buffer[i] - dc_bias) << 5;
    // if (temp > 32767) temp = 32767;
    // if (temp < -32768) temp = -32768;
    time_buffer[i] = (int16_t)temp;
    }
    
    // Step 4: Apply window function
    apply_window(time_buffer);
    
    // Step 5: Calculate FFT
    arm_rfft_q15(&fft_instance, time_buffer, fft_output);
    
    // Step 6: Calculate spectrum energy (magnitude squared)
    arm_cmplx_mag_squared_q15(fft_output, magnitude_buffer, SAMPLE_COUNT / 2);
    
    // Step 7: Display spectrum to LED
    display_fft_on_leds(magnitude_buffer);
    
    sleep_ms(50); // Adjustable refresh rate
    }
    
    int main() {
        stdio_init_all();
    
        init_leds();
        accelerometer_init_once();
        microphone_init_once();
    
        // initialize button GPIO
        gpio_init(BTN_PIN);
        gpio_set_dir(BTN_PIN, GPIO_IN);
        gpio_disable_pulls(BTN_PIN);  
        // Button state management 
        uint8_t current_mode = 0;    // 0 = LED, 1 = ACC, 2 = MIC
        bool last_button_state = false;
    
        while (true) {
            // read the button state
            bool button_state = gpio_get(BTN_PIN);
            if (button_state && !last_button_state) {  
                sleep_ms(5);                          
                if (gpio_get(BTN_PIN)) {
                    current_mode = (current_mode + 1) % 3;
                    clear_leds();                      // clear LEDs on mode switch
                    printf("Switched to mode %d\n", current_mode);
                }
            }
            last_button_state = button_state;
    
            // change the behavior based on the current mode
            switch (current_mode) {
                case 0: leds_iteration();          break;
                case 1: accelerometer_iteration(); break;
                case 2: microphone_iteration();    break;
            }
    
            sleep_ms(50); 
        }
    }

